import 'dart:convert';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/config/peilink_runtime.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/models/life_moment.dart';
import 'package:peijianche_app/services/character_runtime_lifecycle_service.dart';
import 'package:peijianche_app/services/echo_chat_context_service.dart';
import 'package:peijianche_app/services/echo_storage_service.dart';
import 'package:peijianche_app/services/life_moment_storage_service.dart';
import 'package:peijianche_app/services/session_reset_service.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  const channel = MethodChannel('plugins.flutter.io/path_provider');
  late Directory documents;

  setUp(() async {
    PeiLinkRuntime.configure(PeiLinkBuild.unspecified);
    documents = await Directory.systemTemp.createTemp('peilink_reset_test_');
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(channel, (_) async => documents.path);
  });

  tearDown(() async {
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(channel, null);
    if (await documents.exists()) await documents.delete(recursive: true);
  });

  Directory characterDir(String id) =>
      Directory('${documents.path}/characters/$id')
        ..createSync(recursive: true);

  EchoItem echo(String id, String owner, String content) => EchoItem(
    id: id,
    characterId: owner,
    content: content,
    createdAt: DateTime(2026, 8, 21),
    sourceType: EchoSourceType.futureAutoGenerated,
  );

  LifeMomentCandidate moment(String id, String event) => LifeMomentCandidate(
    id: id,
    scene: '桌边',
    event: event,
    detail: '旧生活细节',
    feeling: '平静',
    shareHook: '记录',
    occurredAt: DateTime(2026, 8, 21),
  );

  Future<void> seedRuntime(String id, String marker) async {
    await EchoStorageService(
      characterId: id,
    ).saveItems([echo('old_echo_$id', id, marker)]);
    await LifeMomentStorageService(
      characterId: id,
    ).addItem(moment('old_moment_$id', marker));
    final directory = characterDir(id);
    for (final fileName in [
      'chat_history.json',
      'echo_comments.json',
      'echo_interaction_stats.json',
      'echo_comment_reactions.json',
      'echo_visitors.json',
      'life_event_pool.json',
      'life_decision_history.json',
      'auto_echo_state.json',
      'initiative_state.json',
      'life_traces.json',
      'today_timeline.json',
    ]) {
      await File('${directory.path}/$fileName').writeAsString('[]');
    }
  }

  test('clear chat only leaves Echo, Life and definitions untouched', () async {
    const id = 'character_a';
    await seedRuntime(id, '旧旅行');
    final directory = characterDir(id);
    await File('${directory.path}/character_settings.json').writeAsString('{}');

    await SessionResetService(characterId: id).clearChatOnly();

    expect(await File('${directory.path}/chat_history.json').exists(), isFalse);
    expect(await EchoStorageService(characterId: id).loadItems(), hasLength(1));
    expect(
      await LifeMomentStorageService(characterId: id).loadItems(),
      hasLength(1),
    );
    expect(
      await File('${directory.path}/character_settings.json').exists(),
      isTrue,
    );
  });

  test(
    'runtime reset is character-scoped and preserves durable data',
    () async {
      const target = 'character_a';
      const other = 'character_b';
      await seedRuntime(target, '马尔代夫旧生活');
      await seedRuntime(other, '另一角色生活');
      final directory = characterDir(target);
      final preserved = [
        'character_settings.json',
        'character_profile.json',
        'character_archive.json',
        'memories.json',
        'pending_memories.json',
        'relationship_growth.json',
        'echo_profile.json',
        'echo_space_decoration.json',
      ];
      for (final fileName in preserved) {
        await File(
          '${directory.path}/$fileName',
        ).writeAsString(jsonEncode({'sentinel': fileName}));
      }
      await File(
        '${documents.path}/api_settings.json',
      ).writeAsString('{"sentinel":"api"}');

      await CharacterRuntimeLifecycleService(
        characterId: target,
      ).clearGeneratedLife();

      expect(
        await EchoStorageService(characterId: target).loadItems(),
        isEmpty,
      );
      expect(
        await LifeMomentStorageService(characterId: target).loadItems(),
        isEmpty,
      );
      expect(
        await EchoStorageService(characterId: other).loadItems(),
        hasLength(1),
      );
      expect(
        await LifeMomentStorageService(characterId: other).loadItems(),
        hasLength(1),
      );
      for (final fileName in preserved) {
        expect(
          await File('${directory.path}/$fileName').exists(),
          isTrue,
          reason: '$fileName must survive a runtime reset',
        );
      }
      expect(
        await File('${documents.path}/api_settings.json').exists(),
        isTrue,
      );
    },
  );

  test(
    'reset removes old context and reinitializes exactly once per run',
    () async {
      const id = 'character_a';
      await seedRuntime(id, '马尔代夫旧生活');
      var initializations = 0;
      Future<void> initialize() async {
        initializations++;
        await EchoStorageService(
          characterId: id,
        ).addItem(echo('fresh_initial', id, '新的开始'));
      }

      final reset = SessionResetService(
        characterId: id,
        initializeRuntime: initialize,
      );
      await reset.resetSharedStory();

      expect(initializations, 1);
      expect(
        await EchoStorageService(characterId: id).loadItems(),
        hasLength(1),
      );
      expect(
        await EchoChatContextService(characterId: id).buildFactsSection(),
        isNot(contains('马尔代夫')),
      );

      await reset.resetSharedStory();
      expect(initializations, 2);
      final echoes = await EchoStorageService(characterId: id).loadItems();
      expect(echoes.map((item) => item.id), ['fresh_initial']);
    },
  );
}
