import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/models/echo_comment.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/services/echo_comment_diversity_service.dart';

void main() {
  const service = EchoCommentDiversityService();

  test('semantic duplicate check catches rewritten photo praise', () {
    expect(service.isSemanticallySimilar('光线很好看', '这个照片的光影真的不错'), isTrue);
    expect(service.isSemanticallySimilar('很喜欢这个角度', '这个构图很舒服'), isTrue);
    expect(service.isSemanticallySimilar('事情做完就早点休息', '远处的景色很耐看'), isFalse);
  });

  test('eight comments use eight styles and avoid repeated photo keywords', () {
    final echo = EchoItem(
      id: 'echo-eight',
      characterId: 'role-a',
      content: '加班到很晚，出来吹吹风，顺便看了一会儿远处的夜景。',
      imagePaths: const ['photo.jpg'],
      createdAt: DateTime(2026, 8, 2, 23),
      sourceType: EchoSourceType.futureAutoGenerated,
    );
    final comments = <String>[];
    final used = <EchoCommentStyle>{};
    for (var index = 0; index < 8; index++) {
      final style = service.chooseStyle(
        seed: '${echo.id}|$index',
        used: used,
        virtualVisitor: true,
      );
      final content = service.createTemplate(
        echo: echo,
        style: style,
        seed: '${echo.id}|$index',
        existing: comments,
      );
      used.add(style);
      comments.add(content);
    }

    expect(comments, hasLength(8));
    expect(used, hasLength(8));
    for (final pattern in ['光线', '角度', '氛围', '拍得好']) {
      expect(
        comments.where((comment) => comment.contains(pattern)).length,
        lessThanOrEqualTo(1),
        reason: '$pattern should not be repeated: $comments',
      );
    }
    for (var first = 0; first < comments.length; first++) {
      for (var second = first + 1; second < comments.length; second++) {
        expect(
          service.isSemanticallySimilar(comments[first], comments[second]),
          isFalse,
          reason: '${comments[first]} / ${comments[second]}',
        );
      }
    }
  });

  test('commentStyle persists independently of comment type', () {
    final comment = EchoComment(
      id: 'comment-style',
      echoId: 'echo-style',
      authorType: EchoCommentAuthorType.character,
      content: '忙完记得休息。',
      createdAt: DateTime(2026, 8, 2),
      commentType: EchoCommentType.aiCharacter,
      commentStyle: EchoCommentStyle.care,
    );
    final restored = EchoComment.fromJson(comment.toJson());
    expect(comment.toJson()['commentStyle'], 'care');
    expect(restored.commentStyle, EchoCommentStyle.care);
  });
}
