import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/models/echo_comment.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/services/auto_echo_comment_service.dart';
import 'package:peijianche_app/services/echo_social_interaction_service.dart';

void main() {
  EchoItem echo(String id) => EchoItem(
    id: id,
    characterId: 'owner',
    content: '留下一点今天的记录。',
    createdAt: DateTime.utc(2026, 8, 21),
    sourceType: EchoSourceType.futureAutoGenerated,
  );

  test('immediate simulated comments are deterministically limited to 0-2', () {
    const service = EchoSocialInteractionService();
    final counts = {
      for (var index = 0; index < 60; index++)
        service.immediateTargetFor(echo('echo-$index')),
    };
    expect(counts.every((count) => count >= 0 && count <= 2), isTrue);
    expect(counts, contains(0));
    expect(counts, contains(1));
    expect(counts, contains(2));
  });

  test('virtual residents do not block a delayed AI character comment', () {
    final service = AutoEchoCommentService();
    final allowed = service.canCharacterComment(
      commenterId: 'role-b',
      comments: [
        EchoComment(
          id: 'virtual',
          echoId: 'echo',
          authorType: EchoCommentAuthorType.world,
          authorId: 'virtual-user',
          content: '这一刻很好。',
          createdAt: DateTime.utc(2026, 8, 21),
          commentType: EchoCommentType.virtualUser,
        ),
      ],
    );
    expect(allowed, isTrue);
  });

  test('the same AI character cannot comment twice', () {
    final service = AutoEchoCommentService();
    final allowed = service.canCharacterComment(
      commenterId: 'role-b',
      comments: [
        EchoComment(
          id: 'ai',
          echoId: 'echo',
          authorType: EchoCommentAuthorType.character,
          authorId: 'role-b',
          content: '记得早点休息。',
          createdAt: DateTime.utc(2026, 8, 21),
          sourceType: EchoCommentSourceType.autoCharacter,
          commentType: EchoCommentType.aiCharacter,
        ),
      ],
    );
    expect(allowed, isFalse);
  });
}
