import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/models/ai_character.dart';
import 'package:peijianche_app/models/character_relationship.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/models/echo_visitor_record.dart';
import 'package:peijianche_app/models/relationship_growth.dart';
import 'package:peijianche_app/models/relationship_growth_behavior.dart';
import 'package:peijianche_app/services/character_relationship_storage_service.dart';
import 'package:peijianche_app/services/echo_visitor_social_service.dart';
import 'package:peijianche_app/services/echo_visitor_storage_service.dart';
import 'package:peijianche_app/services/relationship_growth_service.dart';
import 'package:peijianche_app/widgets/echo/echo_recent_visitors_strip.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  const channel = MethodChannel('plugins.flutter.io/path_provider');
  late Directory documentsDirectory;

  setUp(() async {
    documentsDirectory = await Directory.systemTemp.createTemp(
      'echo_social_ecosystem_test_',
    );
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(channel, (call) async {
          if (call.method == 'getApplicationDocumentsDirectory') {
            return documentsDirectory.path;
          }
          return null;
        });
  });

  tearDown(() async {
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(channel, null);
    await documentsDirectory.delete(recursive: true);
  });

  AiCharacter character(String id) => AiCharacter(
    id: id,
    characterName: id,
    remark: '',
    createdAt: DateTime.utc(2026, 1, 1),
  );

  test('AI visitor requires recorded relationship interaction', () async {
    final owner = character('owner');
    final visitor = character('visitor');
    final unrelated = character('unrelated');
    final now = DateTime.utc(2026, 8, 9, 15, 30);
    await CharacterRelationshipStorageService().save(
      CharacterRelationship(
        id: CharacterRelationship.buildId(owner.id, visitor.id),
        characterIdA: owner.id,
        characterIdB: visitor.id,
        stage: CharacterRelationshipStage.acquainted,
        createdAt: now,
        updatedAt: now,
        sharedEventCount: 1,
      ),
    );

    final records = await const EchoVisitorSocialService().synchronize(
      owner: owner,
      characters: [owner, visitor, unrelated],
      now: now,
    );

    expect(
      records.where((item) => item.visitorType == EchoVisitorType.character),
      hasLength(1),
    );
    expect(records.first.visitorId, visitor.id);
  });

  test('user visit remains a separate visitor type', () async {
    final records = await EchoVisitorStorageService(ownerId: 'owner')
        .recordDailyVisit(
          visitorId: 'user',
          visitorName: '你',
          visitorAvatarPath: '',
          now: DateTime.utc(2026, 8, 9),
        );
    expect(records.single.visitorType, EchoVisitorType.user);
  });

  testWidgets('user-only visits are not presented as AI recent visitors', (
    tester,
  ) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: EchoRecentVisitorsStrip(
            visitors: [
              EchoVisitorRecord(
                id: 'user-visit',
                spaceOwnerId: 'owner',
                visitorId: 'user',
                visitorType: EchoVisitorType.user,
                visitTime: DateTime.now(),
              ),
            ],
            onTap: () {},
          ),
        ),
      ),
    );
    expect(find.text('这里还没有留下痕迹'), findsOneWidget);
    expect(find.textContaining('1 人来过'), findsNothing);
  });

  test('new Echo social types survive JSON round trip', () {
    for (final type in [EchoLifeType.collection, EchoLifeType.memory]) {
      final restored = EchoItem.fromJson(
        EchoItem(
          id: type.name,
          characterId: 'role',
          content: 'content',
          createdAt: DateTime.utc(2026, 8, 9),
          sourceType: EchoSourceType.futureAutoGenerated,
          lifeType: type,
        ).toJson(),
      );
      expect(restored.lifeType, type);
    }
  });

  test('growth changes tendencies without locking features', () {
    final low = RelationshipGrowthBehavior.forLevel(5);
    final high = RelationshipGrowthBehavior.forLevel(95);
    expect(high.shareChanceModifier, greaterThan(low.shareChanceModifier));
    expect(high.personalSharingBias, greaterThan(low.personalSharingBias));
    expect(high.memoryReferenceBias, greaterThan(low.memoryReferenceBias));
  });

  test('crossing a configured milestone invokes the hook once', () async {
    final hook = _CaptureHook();
    final service = RelationshipGrowthService(
      characterId: 'milestone-role',
      milestoneHooks: [hook],
    );
    final now = DateTime.utc(2026, 8, 9);
    await service.save(
      RelationshipGrowthProfile(
        characterId: 'milestone-role',
        totalExperience: 1610,
        history: const [],
        gifts: const [],
        createdAt: now,
        updatedAt: now,
      ),
    );

    await service.giveGift(RelationshipGiftType.letter, at: now);
    expect(hook.levels, [10]);
  });
}

class _CaptureHook implements RelationshipGrowthMilestoneHook {
  final List<int> levels = [];

  @override
  Future<void> onMilestone(RelationshipGrowthMilestone milestone) async {
    levels.add(milestone.level);
  }
}
