import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/models/ai_character.dart';
import 'package:peijianche_app/models/echo_comment.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/services/echo_comment_author_service.dart';
import 'package:peijianche_app/services/echo_interaction_stats_service.dart';

void main() {
  EchoItem echo(String id) => EchoItem(
    id: id,
    characterId: 'owner',
    content: '今天的一点记录。',
    createdAt: DateTime.utc(2026, 8, 21),
    sourceType: EchoSourceType.futureAutoGenerated,
  );

  test('new interaction baselines are stable and include quiet posts', () {
    final service = EchoInteractionStatsService(ownerId: 'test-owner');
    final first = service.baselineFor(echo('same'), hasRelationship: false);
    final second = service.baselineFor(echo('same'), hasRelationship: false);
    expect(second.viewCount, first.viewCount);
    expect(second.likeCount, first.likeCount);
    expect(second.collectCount, first.collectCount);

    final samples = List.generate(
      80,
      (index) => service.baselineFor(
        echo('echo-$index'),
        hasRelationship: false,
      ),
    );
    expect(samples.any((stats) => stats.viewCount < 30), isTrue);
    expect(samples.any((stats) => stats.likeCount == 0), isTrue);
    expect(samples.any((stats) => stats.viewCount >= 90), isTrue);
  });

  test('only registered AI comment authors can open a character space', () {
    final character = AiCharacter(
      id: 'role-a',
      characterName: '阿澈',
      remark: '',
      createdAt: DateTime.utc(2026),
    );
    EchoComment comment(EchoCommentType type, String authorId) => EchoComment(
      id: '$type-$authorId',
      echoId: 'echo',
      authorType: type == EchoCommentType.aiCharacter
          ? EchoCommentAuthorType.character
          : EchoCommentAuthorType.world,
      authorId: authorId,
      content: '路过看看。',
      createdAt: DateTime.utc(2026),
      commentType: type,
    );

    expect(
      EchoCommentAuthorService.characterFor(
        comment(EchoCommentType.aiCharacter, 'role-a'),
        [character],
      ),
      same(character),
    );
    expect(
      EchoCommentAuthorService.characterFor(
        comment(EchoCommentType.virtualUser, 'role-a'),
        [character],
      ),
      isNull,
    );
    expect(
      EchoCommentAuthorService.characterFor(
        comment(EchoCommentType.aiCharacter, 'missing'),
        [character],
      ),
      isNull,
    );
  });
}
