import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/services/echo_duplicate_guard.dart';

void main() {
  const guard = EchoDuplicateGuard();

  EchoItem old(String content) => EchoItem(
    id: content,
    characterId: 'role',
    content: content,
    createdAt: DateTime.utc(2026, 8, 21),
    sourceType: EchoSourceType.futureAutoGenerated,
  );

  test('exact and punctuation-only differences are duplicates', () {
    for (final content in ['今天有点累。', ' 今天有点累！ ']) {
      final result = guard.checkAgainst(
        content: content,
        items: [old('今天有点累')],
        threshold: EchoDuplicateGuard.sameCharacterThreshold,
        scope: 'same_character',
      );
      expect(result.isDuplicate, isTrue);
    }
  });

  test('highly similar wording is detected', () {
    final result = guard.checkAgainst(
      content: '今天总算忙完事情了，准备早点休息。',
      items: [old('今天终于把事情忙完了，准备早点休息。')],
      threshold: EchoDuplicateGuard.sameCharacterThreshold,
      scope: 'same_character',
    );
    expect(result.isDuplicate, isTrue);
  });

  test('same topic with materially different content is allowed', () {
    final result = guard.checkAgainst(
      content: '下雨天果然适合睡觉。',
      items: [old('今天下雨了。')],
      threshold: EchoDuplicateGuard.sameCharacterThreshold,
      scope: 'same_character',
    );
    expect(result.isDuplicate, isFalse);
  });

  test('public threshold blocks exact cross-character copies', () {
    final result = guard.checkAgainst(
      content: '新的地方，先留一点记录。',
      items: [old('新的地方，先留一点记录！')],
      threshold: EchoDuplicateGuard.publicFeedThreshold,
      scope: 'public_feed',
    );
    expect(result.isDuplicate, isTrue);
  });

  test(
    'automatic generation retries at most once and accepts a rewrite',
    () async {
      var calls = 0;
      final result = await guard.acceptOrRetryOnce(
        initial: 'duplicate',
        isDuplicate: (value) async => value == 'duplicate',
        retry: () async {
          calls++;
          return 'rewritten';
        },
      );
      expect(calls, 1);
      expect(result, 'rewritten');
    },
  );

  test('automatic generation gives up when the single retry repeats', () async {
    var calls = 0;
    final result = await guard.acceptOrRetryOnce(
      initial: 'duplicate',
      isDuplicate: (value) async => value == 'duplicate',
      retry: () async {
        calls++;
        return 'duplicate';
      },
    );
    expect(calls, 1);
    expect(result, isNull);
  });
}
