import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/models/echo_space_summary.dart';
import 'package:peijianche_app/widgets/echo/echo_space_overview.dart';

void main() {
  test('space summary uses existing Echo and interaction data', () {
    final now = DateTime(2026, 8, 9, 12);
    final summary = EchoSpaceSummary.fromExistingData(
      echoes: [
        EchoItem(
          id: 'echo-1',
          characterId: 'student-role',
          content: '记录今天',
          createdAt: now.subtract(const Duration(hours: 2)),
          sourceType: EchoSourceType.futureAutoGenerated,
          lifeType: EchoLifeType.workStudy,
          characterState: '学习中',
        ),
      ],
      interactionCount: 18,
      sharedExperienceCount: 3,
      now: now,
    );

    expect(summary.currentStatus, '学习中');
    expect(summary.recentActivity, '近7天发布了 1 条动态');
    expect(summary.interactionCount, 18);
    expect(summary.sharedExperienceCount, 3);
  });

  test('empty legacy space receives neutral generic defaults', () {
    final summary = EchoSpaceSummary.fromExistingData(
      echoes: const [],
      interactionCount: -1,
      sharedExperienceCount: -1,
    );

    expect(summary.currentStatus, '安静生活中');
    expect(summary.recentActivity, '最近暂无新动态');
    expect(summary.interactionCount, 0);
    expect(summary.sharedExperienceCount, 0);
  });

  testWidgets('space overview shows status and opens interaction summary', (
    tester,
  ) async {
    var opened = false;
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Column(
            children: [
              const EchoCharacterActivityStrip(
                currentStatus: '探索中',
                recentActivity: '近7天发布了 2 条动态',
              ),
              EchoInteractionSummaryEntry(
                interactionCount: 12,
                sharedExperienceCount: 4,
                onTap: () => opened = true,
              ),
            ],
          ),
        ),
      ),
    );

    expect(find.text('探索中'), findsOneWidget);
    expect(find.text('近7天发布了 2 条动态'), findsOneWidget);
    expect(find.text('12 次互动 · 4 条共同经历'), findsOneWidget);
    await tester.tap(
      find.byKey(const ValueKey('echo-interaction-summary-entry')),
    );
    expect(opened, isTrue);
  });
}
