import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/models/ai_character.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/models/life_feed_entry.dart';
import 'package:peijianche_app/models/life_moment.dart';
import 'package:peijianche_app/models/life_trace.dart';
import 'package:peijianche_app/services/life_feed_service.dart';

void main() {
  AiCharacter character(String id, String name) => AiCharacter(
    id: id,
    characterName: name,
    remark: '',
    createdAt: DateTime(2026, 1, 1),
  );

  test(
    'aggregates real activity across characters and sorts newest first',
    () async {
      final service = LifeFeedService(
        loadMoments: (id) async => id == 'a'
            ? [
                LifeMomentCandidate(
                  id: 'meeting',
                  scene: '公司',
                  event: '刚结束了一场会议',
                  detail: '',
                  feeling: '',
                  shareHook: '',
                  occurredAt: DateTime(2026, 8, 21, 10),
                ),
              ]
            : [],
        loadEchoes: (id) async => id == 'b'
            ? [
                EchoItem(
                  id: 'echo_b',
                  characterId: id,
                  content: '去了俱乐部',
                  createdAt: DateTime(2026, 8, 21, 11),
                  sourceType: EchoSourceType.futureAutoGenerated,
                ),
              ]
            : [],
        loadTraces: (_) async => [],
      );

      final result = await service.load([
        character('a', '裴简澈'),
        character('b', '车云千'),
      ]);

      expect(result.map((item) => item.character.id), ['b', 'a']);
      expect(result.map((item) => item.summary), ['去了俱乐部', '刚结束了一场会议']);
    },
  );

  test(
    'deduplicates an Echo and Life Moment with the same source id',
    () async {
      final sourceTime = DateTime(2026, 8, 21, 10);
      final role = character('a', '裴简澈');
      final service = LifeFeedService(
        loadMoments: (_) async => [
          LifeMomentCandidate(
            id: 'same_life_event',
            scene: '咖啡店',
            event: '喝了咖啡',
            detail: '',
            feeling: '',
            shareHook: '',
            occurredAt: sourceTime,
          ),
        ],
        loadEchoes: (_) async => [
          EchoItem(
            id: 'echo_a',
            characterId: 'a',
            content: '发布了一条关于咖啡的 Echo',
            createdAt: sourceTime.add(const Duration(minutes: 1)),
            sourceType: EchoSourceType.futureAutoGenerated,
            sourceLifeEventId: 'same_life_event',
          ),
        ],
        loadTraces: (_) async => [
          LifeTrace(
            id: 'conversation_day',
            kind: 'conversation',
            title: '和你聊了一会儿',
            emoji: '💬',
            detail: '',
            occurredAt: sourceTime.subtract(const Duration(minutes: 1)),
          ),
        ],
      );

      final result = await service.load([role]);

      expect(
        result.where((item) => item.dedupeKey.contains('same_life_event')),
        hasLength(1),
      );
      expect(result.first.source, LifeFeedSource.echo);
      expect(result, hasLength(2));
    },
  );

  test('returns an empty feed when there are no characters', () async {
    final result = await LifeFeedService().load(const []);
    expect(result, isEmpty);
  });
}
