import 'package:flutter_test/flutter_test.dart';
import 'package:peijianche_app/models/ai_character.dart';
import 'package:peijianche_app/models/character_profile.dart';
import 'package:peijianche_app/models/echo_item.dart';
import 'package:peijianche_app/services/auto_echo_policy.dart';
import 'package:peijianche_app/services/echo_daily_life_service.dart';

void main() {
  const lifeService = EchoDailyLifeService();
  const policy = AutoEchoPolicy();
  final baseTime = DateTime(2026, 8, 9, 18, 30);

  AiCharacter character(String id) => AiCharacter(
    id: id,
    characterName: id,
    remark: '',
    createdAt: DateTime(2026, 1, 1),
  );

  test('legacy Echo JSON remains readable with universal defaults', () {
    final restored = EchoItem.fromJson({
      'id': 'legacy',
      'characterId': 'role',
      'content': 'old echo',
      'createdAt': baseTime.toIso8601String(),
      'sourceType': 'futureAutoGenerated',
    });

    expect(restored.lifeType, EchoLifeType.daily);
    expect(restored.sourceEvent, isEmpty);
    expect(restored.characterState, isEmpty);
    expect(restored.commentsEnabled, isTrue);
  });

  test('universal Echo metadata survives JSON round trip', () {
    final item = EchoItem(
      id: 'new',
      characterId: 'role',
      content: 'life',
      createdAt: baseTime,
      sourceType: EchoSourceType.futureAutoGenerated,
      lifeType: EchoLifeType.interaction,
      sourceEvent: 'recent_user_interaction',
      characterState: '思考中',
      commentsEnabled: false,
    );
    final restored = EchoItem.fromJson(item.toJson());

    expect(restored.lifeType, EchoLifeType.interaction);
    expect(restored.sourceEvent, 'recent_user_interaction');
    expect(restored.characterState, '思考中');
    expect(restored.commentsEnabled, isFalse);
  });

  test('characters receive independent activity windows and publish times', () {
    final patterns = <String>{};
    final times = <DateTime>{};
    for (var index = 0; index < 12; index++) {
      final id = 'role-$index';
      final pattern = policy.activityPattern(id);
      patterns.add(
        '${pattern.preferredStartHour}-${pattern.preferredEndHour}-${pattern.quietCycleDays}',
      );
      times.add(
        policy.distributedCreatedAt(
          characterId: id,
          now: baseTime,
          trigger: 'daily',
        ),
      );
    }

    expect(patterns.length, greaterThan(3));
    expect(times.length, greaterThan(6));
    expect(times.every((time) => time.isBefore(baseTime)), isTrue);
  });

  test(
    'recent interaction produces interaction traces without relationship assumptions',
    () {
      final generated = <EchoLifeType>{};
      final contents = <String>[];
      for (var day = 1; day <= 24; day++) {
        final life = lifeService.create(
          character: character('social-role'),
          at: DateTime(2026, 8, day),
          recentUserMessages: 12,
        );
        generated.add(life.lifeType);
        contents.add(life.content);
      }

      expect(generated, contains(EchoLifeType.interaction));
      expect(contents.where((text) => text.contains('恋人')), isEmpty);
      expect(contents.where((text) => text.contains('夫妻')), isEmpty);
    },
  );

  test('structured student profile enables matching work-study life', () {
    const profile = CharacterProfile(
      characterId: 'student',
      age: '17',
      identity: '学生',
      occupation: '高中生',
      personalityTags: '安静、认真',
      worldview: '现代校园',
    );
    final items = [
      for (var day = 1; day <= 31; day++)
        lifeService.create(
          character: character('student'),
          profile: profile,
          at: DateTime(2026, 8, day),
        ),
    ];

    final workItems = items.where(
      (item) => item.lifeType == EchoLifeType.workStudy,
    );
    expect(workItems, isNotEmpty);
    expect(workItems.any((item) => item.sourceEvent.contains('高中生')), isTrue);
  });

  test(
    'fantasy worldview enables world observations without fixed persona',
    () {
      const profile = CharacterProfile(
        characterId: 'fantasy',
        identity: '旅行者',
        personalityTags: '谨慎、好奇',
        worldview: '生活在有魔法与龙的幻想世界',
      );
      final items = [
        for (var day = 1; day <= 31; day++)
          lifeService.create(
            character: character('fantasy'),
            profile: profile,
            at: DateTime(2026, 9, day),
          ),
      ];

      expect(
        items.any((item) => item.sourceEvent == 'worldview_observation'),
        isTrue,
      );
    },
  );

  test('recent summaries steer fallback generation away from repetition', () {
    final first = lifeService.create(
      character: character('repeat-guard'),
      at: baseTime,
    );
    final second = lifeService.create(
      character: character('repeat-guard'),
      at: baseTime,
      excludedSummaries: [first.summary],
    );

    expect(second.summary, isNot(first.summary));
  });
}
