import '../models/ai_character.dart';
import '../models/echo_item.dart';
import 'auto_echo_state_service.dart';
import 'character_registry_service.dart';
import 'echo_generation_service.dart';
import 'echo_storage_service.dart';
import 'life_event_pool_service.dart';
import 'life_moment_storage_service.dart';
import 'shared_world_event_service.dart';

class AutoEchoReport {
  const AutoEchoReport({required this.checked, required this.published});
  final int checked;
  final int published;
}

class AutoEchoService {
  static bool _running = false;
  static const Duration _minimumCheckInterval = Duration(hours: 2);
  static const Duration _minimumPublishGap = Duration(hours: 6);

  final CharacterRegistryService _registry = CharacterRegistryService();

  Future<AutoEchoReport> checkAll({DateTime? now}) async {
    if (_running) return const AutoEchoReport(checked: 0, published: 0);
    _running = true;
    try {
      final time = now ?? DateTime.now();
      final characters = await _registry.loadCharacters();
      var checked = 0;
      var published = 0;
      for (final character in characters) {
        checked++;
        if (await _checkCharacter(character, time)) published++;
      }
      return AutoEchoReport(checked: checked, published: published);
    } finally {
      _running = false;
    }
  }

  Future<bool> _checkCharacter(AiCharacter character, DateTime now) async {
    final stateService = AutoEchoStateService(characterId: character.id);
    var state = await stateService.load(now: now);

    if (state.lastCheckedAt != null &&
        now.difference(state.lastCheckedAt!) < _minimumCheckInterval) {
      return false;
    }

    state = state.copyWith(lastCheckedAt: now);
    await stateService.save(state);

    if (state.publishedToday >= 2) return false;
    if (state.lastPublishedAt != null &&
        now.difference(state.lastPublishedAt!) < _minimumPublishGap) {
      return false;
    }

    final generation = EchoGenerationService(character: character);
    try {
      final draft = await generation.tryGenerateDraft(manualRequest: false);
      final decision = generation.lastDecision;
      if (draft == null || decision == null || !decision.shouldShare) return false;

      final summary = draft.momentSummary.trim();
      if (summary.isNotEmpty &&
          state.recentSummaries.any((old) => _similar(old, summary))) {
        return false;
      }

      final item = EchoItem(
        id: 'auto_echo_${now.microsecondsSinceEpoch}',
        characterId: character.id,
        content: draft.content,
        createdAt: now,
        sourceType: EchoSourceType.futureAutoGenerated,
        imagePrompt: draft.imageScene,
        imageStatus: draft.imageScene.isEmpty ? 'not_needed' : 'pending',
        imagePath: '',
      );
      await EchoStorageService(characterId: character.id).addItem(item);

      final selected = decision.candidate;
      final confirmed = selected.copyWith(occurredAt: now);
      await LifeMomentStorageService(characterId: character.id).addItem(confirmed);
      await LifeEventPoolService(characterId: character.id)
          .markUsed(selected.id, now: now);
      await SharedWorldEventService().recordConfirmedMoment(
        originCharacter: character,
        moment: confirmed,
        occurredAt: now,
      );

      final summaries = <String>[summary, ...state.recentSummaries]
          .where((value) => value.trim().isNotEmpty)
          .take(8)
          .toList();
      await stateService.save(state.copyWith(
        publishedToday: state.publishedToday + 1,
        lastPublishedAt: now,
        recentSummaries: summaries,
      ));
      return true;
    } catch (_) {
      // 自动 Echo 是生活展示层，失败不能阻塞世界推进或应用启动。
      return false;
    } finally {
      generation.dispose();
    }
  }

  bool _similar(String a, String b) {
    String normalize(String value) => value
        .toLowerCase()
        .replaceAll(RegExp(r'\s+'), '')
        .replaceAll(RegExp(r'[，。！？、,.!?：:；;\-—_]'), '');
    final left = normalize(a);
    final right = normalize(b);
    if (left.isEmpty || right.isEmpty) return false;
    return left == right || left.contains(right) || right.contains(left);
  }
}
