import 'dart:convert';

import '../models/echo_interaction_stats.dart';
import '../models/echo_item.dart';
import 'character_scope_service.dart';

class EchoInteractionStatsService {
  EchoInteractionStatsService({required String ownerId})
    : _scope = CharacterScopeService(ownerId);

  static const _fileName = 'echo_interaction_stats.json';
  final CharacterScopeService _scope;

  Future<void> clear() async {
    final file = await _scope.dataFile(_fileName);
    if (await file.exists()) await file.delete();
  }

  Future<Map<String, EchoInteractionStats>> loadOrCreate(
    List<EchoItem> items, {
    required bool hasRelationship,
  }) async {
    final file = await _scope.dataFile(_fileName);
    final saved = <String, EchoInteractionStats>{};
    if (await file.exists()) {
      try {
        final decoded = jsonDecode(await file.readAsString());
        if (decoded is List) {
          for (final raw in decoded.whereType<Map>()) {
            final stats = EchoInteractionStats.fromJson(raw);
            if (stats.echoId.isNotEmpty) saved[stats.echoId] = stats;
          }
        }
      } catch (_) {}
    }

    var changed = false;
    for (final item in items) {
      if (saved.containsKey(item.id)) continue;
      saved[item.id] = baselineFor(item, hasRelationship: hasRelationship);
      changed = true;
    }
    if (changed) {
      await file.writeAsString(
        jsonEncode(saved.values.map((item) => item.toJson()).toList()),
        flush: true,
      );
    }
    return saved;
  }

  Future<EchoInteractionStats> createForEcho(
    EchoItem item, {
    required int commentCount,
    required bool hasRelationship,
  }) async {
    final all = await loadOrCreate([item], hasRelationship: hasRelationship);
    final generated =
        all[item.id] ?? baselineFor(item, hasRelationship: hasRelationship);
    final updated = EchoInteractionStats(
      echoId: generated.echoId,
      viewCount: generated.viewCount,
      likeCount: generated.likeCount,
      commentCount: commentCount,
      collectCount: generated.collectCount,
      heatLevel: generated.heatLevel,
      realLikeCount: generated.realLikeCount,
      virtualLikeCount: generated.virtualLikeCount,
    );
    all[item.id] = updated;
    final file = await _scope.dataFile(_fileName);
    await file.writeAsString(
      jsonEncode(all.values.map((value) => value.toJson()).toList()),
      flush: true,
    );
    return updated;
  }

  /// A stable baseline for newly seen Echoes. Existing persisted statistics
  /// are never regenerated by this method.
  EchoInteractionStats baselineFor(
    EchoItem item, {
    required bool hasRelationship,
  }) {
    final seed = _stableHash('${item.id}|${item.createdAt.toIso8601String()}');
    final important = item.sourceSharedExperienceId.trim().isNotEmpty;
    final special = !important && item.sourceLifeEventId.trim().isNotEmpty;
    final roll = seed % 100;
    final imageBoost = item.imagePaths.isNotEmpty ? 6 : 0;
    final relationBoost = hasRelationship ? 4 : 0;
    late final int views;
    late final int likes;
    late final int collects;
    if (important) {
      views = 120 + seed % 301;
      likes = 12 + seed % 39;
      collects = 2 + seed % 8;
    } else if (special || roll >= 90) {
      views = 90 + seed % 211 + imageBoost + relationBoost;
      likes = 7 + seed % 29;
      collects = 1 + seed % 6;
    } else if (roll < 35) {
      views = 3 + seed % 22 + imageBoost;
      likes = seed % 3;
      collects = 0;
    } else {
      views = 20 + seed % 91 + imageBoost + relationBoost;
      likes = 1 + seed % 10;
      collects = seed % 3;
    }
    return EchoInteractionStats(
      echoId: item.id,
      viewCount: views,
      likeCount: likes,
      commentCount: 0,
      collectCount: collects,
      heatLevel: important
          ? EchoHeatLevel.commemorative
          : (special || views >= 150)
          ? EchoHeatLevel.popular
          : EchoHeatLevel.calm,
    );
  }

  int _stableHash(String value) {
    var hash = 17;
    for (final unit in value.codeUnits) {
      hash = ((hash * 37) + unit) & 0x7fffffff;
    }
    return hash;
  }
}
