import 'echo_comment.dart';

enum EchoSourceType { manual, aiGenerated, futureAutoGenerated }

enum EchoLifeType {
  daily,
  interest,
  workStudy,
  environment,
  mood,
  interaction,
  arrival,
  collection,
  memory,
}

extension EchoLifeTypeLabel on EchoLifeType {
  String get label => switch (this) {
    EchoLifeType.daily => '日常',
    EchoLifeType.interest => '兴趣',
    EchoLifeType.workStudy => '工作学习',
    EchoLifeType.environment => '环境观察',
    EchoLifeType.mood => '情绪状态',
    EchoLifeType.interaction => '互动痕迹',
    EchoLifeType.arrival => '初次到来',
    EchoLifeType.collection => '收藏',
    EchoLifeType.memory => '记忆',
  };
}

class EchoItem {
  const EchoItem({
    required this.id,
    required this.characterId,
    required this.content,
    required this.createdAt,
    required this.sourceType,
    this.imagePaths = const [],
    this.isLiked = false,
    this.likeCount = 0,
    this.isCollected = false,
    this.comments = const [],
    this.imagePrompt = '',
    this.imageStatus = 'none',
    this.imagePath = '',
    this.sourceLifeEventId = '',
    this.sourceSharedExperienceId = '',
    this.lifeType = EchoLifeType.daily,
    this.sourceEvent = '',
    this.characterState = '',
    this.commentsEnabled = true,
  });

  final String id;
  final String characterId;
  final String content;
  final List<String> imagePaths;
  final DateTime createdAt;
  final EchoSourceType sourceType;
  final bool isLiked;
  final int likeCount;
  final bool isCollected;
  final List<EchoComment> comments;
  final String imagePrompt;
  final String imageStatus;
  final String imagePath;
  final String sourceLifeEventId;
  final String sourceSharedExperienceId;

  /// Product-level life metadata. Defaults keep every legacy Echo readable.
  final EchoLifeType lifeType;
  final String sourceEvent;
  final String characterState;
  final bool commentsEnabled;

  bool get isFromSharedExperience => sourceSharedExperienceId.trim().isNotEmpty;

  EchoItem copyWith({
    String? content,
    List<String>? imagePaths,
    DateTime? createdAt,
    EchoSourceType? sourceType,
    bool? isLiked,
    int? likeCount,
    bool? isCollected,
    List<EchoComment>? comments,
    String? imagePrompt,
    String? imageStatus,
    String? imagePath,
    String? sourceLifeEventId,
    String? sourceSharedExperienceId,
    EchoLifeType? lifeType,
    String? sourceEvent,
    String? characterState,
    bool? commentsEnabled,
  }) {
    return EchoItem(
      id: id,
      characterId: characterId,
      content: content ?? this.content,
      imagePaths: imagePaths ?? this.imagePaths,
      createdAt: createdAt ?? this.createdAt,
      sourceType: sourceType ?? this.sourceType,
      isLiked: isLiked ?? this.isLiked,
      likeCount: likeCount ?? this.likeCount,
      isCollected: isCollected ?? this.isCollected,
      comments: comments ?? this.comments,
      imagePrompt: imagePrompt ?? this.imagePrompt,
      imageStatus: imageStatus ?? this.imageStatus,
      imagePath: imagePath ?? this.imagePath,
      sourceLifeEventId: sourceLifeEventId ?? this.sourceLifeEventId,
      sourceSharedExperienceId:
          sourceSharedExperienceId ?? this.sourceSharedExperienceId,
      lifeType: lifeType ?? this.lifeType,
      sourceEvent: sourceEvent ?? this.sourceEvent,
      characterState: characterState ?? this.characterState,
      commentsEnabled: commentsEnabled ?? this.commentsEnabled,
    );
  }

  Map<String, dynamic> toJson({bool includeComments = true}) => {
    'id': id,
    'characterId': characterId,
    'content': content,
    'imagePaths': imagePaths,
    'createdAt': createdAt.toIso8601String(),
    'sourceType': sourceType.name,
    'isLiked': isLiked,
    'likeCount': likeCount,
    'isCollected': isCollected,
    'comments': includeComments
        ? comments.map((comment) => comment.toJson()).toList()
        : const [],
    'imagePrompt': imagePrompt,
    'imageStatus': imageStatus,
    'imagePath': imagePath,
    'sourceLifeEventId': sourceLifeEventId,
    'sourceSharedExperienceId': sourceSharedExperienceId,
    'lifeType': lifeType.name,
    'sourceEvent': sourceEvent,
    'characterState': characterState,
    'commentsEnabled': commentsEnabled,
  };

  factory EchoItem.fromJson(Map<dynamic, dynamic> json) {
    final rawImages = json['imagePaths'];
    final legacyImagePath = json['imagePath']?.toString().trim() ?? '';
    final parsedImagePaths = rawImages is List
        ? rawImages
              .map((item) => item.toString().trim())
              .where((item) => item.isNotEmpty)
              .toList()
        : <String>[];
    if (legacyImagePath.isNotEmpty &&
        !parsedImagePaths.contains(legacyImagePath)) {
      parsedImagePaths.add(legacyImagePath);
    }
    final rawComments = json['comments'];
    return EchoItem(
      id: json['id']?.toString() ?? '',
      characterId: json['characterId']?.toString() ?? '',
      content: json['content']?.toString() ?? '',
      imagePaths: parsedImagePaths,
      createdAt:
          DateTime.tryParse(json['createdAt']?.toString() ?? '') ??
          DateTime.now(),
      sourceType: EchoSourceType.values.firstWhere(
        (value) => value.name == json['sourceType']?.toString(),
        orElse: () => EchoSourceType.manual,
      ),
      isLiked: json['isLiked'] == true,
      likeCount: int.tryParse(json['likeCount']?.toString() ?? '') ?? 0,
      isCollected: json['isCollected'] == true,
      comments: rawComments is List
          ? rawComments
                .whereType<Map>()
                .map(
                  (item) => EchoComment.fromJson(
                    item,
                    fallbackEchoId: json['id']?.toString() ?? '',
                  ),
                )
                .toList()
          : const [],
      imagePrompt: json['imagePrompt']?.toString() ?? '',
      imageStatus: json['imageStatus']?.toString() ?? 'none',
      imagePath: legacyImagePath,
      sourceLifeEventId: json['sourceLifeEventId']?.toString() ?? '',
      sourceSharedExperienceId:
          json['sourceSharedExperienceId']?.toString() ?? '',
      lifeType: EchoLifeType.values.firstWhere(
        (value) => value.name == json['lifeType']?.toString(),
        orElse: () => EchoLifeType.daily,
      ),
      sourceEvent: json['sourceEvent']?.toString() ?? '',
      characterState: json['characterState']?.toString() ?? '',
      commentsEnabled: json['commentsEnabled'] != false,
    );
  }
}
