enum EchoSourceType {
  manual,
  aiGenerated,
  futureAutoGenerated,
}

enum EchoAuthorType {
  user,
  character,
}

class EchoComment {
  const EchoComment({
    required this.id,
    required this.authorType,
    required this.content,
    required this.createdAt,
    this.replyToCommentId,
  });

  final String id;
  final EchoAuthorType authorType;
  final String content;
  final DateTime createdAt;
  final String? replyToCommentId;

  Map<String, dynamic> toJson() => {
        'id': id,
        'authorType': authorType.name,
        'content': content,
        'createdAt': createdAt.toIso8601String(),
        'replyToCommentId': replyToCommentId,
      };

  factory EchoComment.fromJson(Map<dynamic, dynamic> json) {
    return EchoComment(
      id: json['id']?.toString() ?? '',
      authorType: EchoAuthorType.values.firstWhere(
        (value) => value.name == json['authorType']?.toString(),
        orElse: () => EchoAuthorType.user,
      ),
      content: json['content']?.toString() ?? '',
      createdAt: DateTime.tryParse(json['createdAt']?.toString() ?? '') ??
          DateTime.now(),
      replyToCommentId: json['replyToCommentId']?.toString(),
    );
  }
}

class EchoItem {
  const EchoItem({
    required this.id,
    required this.characterId,
    required this.content,
    required this.createdAt,
    required this.sourceType,
    this.imagePaths = const [],
    this.isLiked = false,
    this.likeCount = 0,
    this.isCollected = false,
    this.comments = const [],
    this.imagePrompt = '',
    this.imageStatus = 'none',
    this.imagePath = '',
  });

  final String id;
  final String characterId;
  final String content;
  final List<String> imagePaths;
  final DateTime createdAt;
  final EchoSourceType sourceType;
  final bool isLiked;
  final int likeCount;
  final bool isCollected;
  final List<EchoComment> comments;
  final String imagePrompt;
  final String imageStatus;
  final String imagePath;

  EchoItem copyWith({
    String? content,
    List<String>? imagePaths,
    DateTime? createdAt,
    EchoSourceType? sourceType,
    bool? isLiked,
    int? likeCount,
    bool? isCollected,
    List<EchoComment>? comments,
    String? imagePrompt,
    String? imageStatus,
    String? imagePath,
  }) {
    return EchoItem(
      id: id,
      characterId: characterId,
      content: content ?? this.content,
      imagePaths: imagePaths ?? this.imagePaths,
      createdAt: createdAt ?? this.createdAt,
      sourceType: sourceType ?? this.sourceType,
      isLiked: isLiked ?? this.isLiked,
      likeCount: likeCount ?? this.likeCount,
      isCollected: isCollected ?? this.isCollected,
      comments: comments ?? this.comments,
      imagePrompt: imagePrompt ?? this.imagePrompt,
      imageStatus: imageStatus ?? this.imageStatus,
      imagePath: imagePath ?? this.imagePath,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'characterId': characterId,
        'content': content,
        'imagePaths': imagePaths,
        'createdAt': createdAt.toIso8601String(),
        'sourceType': sourceType.name,
        'isLiked': isLiked,
        'likeCount': likeCount,
        'isCollected': isCollected,
        'comments': comments.map((comment) => comment.toJson()).toList(),
        'imagePrompt': imagePrompt,
        'imageStatus': imageStatus,
        'imagePath': imagePath,
      };

  factory EchoItem.fromJson(Map<dynamic, dynamic> json) {
    final rawImages = json['imagePaths'];
    final rawComments = json['comments'];

    return EchoItem(
      id: json['id']?.toString() ?? '',
      characterId: json['characterId']?.toString() ?? '',
      content: json['content']?.toString() ?? '',
      imagePaths: rawImages is List
          ? rawImages.map((item) => item.toString()).toList()
          : const [],
      createdAt: DateTime.tryParse(json['createdAt']?.toString() ?? '') ??
          DateTime.now(),
      sourceType: EchoSourceType.values.firstWhere(
        (value) => value.name == json['sourceType']?.toString(),
        orElse: () => EchoSourceType.manual,
      ),
      isLiked: json['isLiked'] == true,
      likeCount: int.tryParse(json['likeCount']?.toString() ?? '') ?? 0,
      isCollected: json['isCollected'] == true,
      comments: rawComments is List
          ? rawComments
              .whereType<Map>()
              .map(EchoComment.fromJson)
              .toList()
          : const [],
      imagePrompt: json['imagePrompt']?.toString() ?? '',
      imageStatus: json['imageStatus']?.toString() ?? 'none',
      imagePath: json['imagePath']?.toString() ?? '',
    );
  }
}
